### PR TITLE
Duplicate serial number fix

### PR DESCRIPTION
**Pull request by drsib**
Fix to issue 13 where the serial number was being duplicated across all devices.

### CODE REVIEW

**Comment by thk-socal** [comment]
@sbozarth would you approve this to the repo and perhaps consider giving one or two people write access for future changes?

**Review by sbozarth — APPROVED** [review]

**Review by sbozarth — APPROVED** [review]

**Comment by sbozarth** [comment]
I know next to nothing about github, so I was finally able to sit down and look at this.

I (think I) committed the changes. I don't necessarily have an issue with granting access. I gather I should "invite collaborator". Are you volunteering?

There is also the issue of pushing npm updates. Can I do the same there?







On Friday, April 15, 2022, 11:00:26 AM PDT, thk-socal ***@***.***> wrote: 







@sbozarth would you approve this to the repo and perhaps consider giving one or two people write access for future changes?

**Comment by drsib** [comment]
I will be honest, it took me a while to figure out the branching and pull requests! So I'm probably not the best person to help. But I suspect you can publish it to npm? Probably the same process as to how it was put there in the first place?

**Comment by thk-socal** [comment]
@sbozarth you will need to release a new version as well. Perhaps 1.2.1 or 1.3.0 in essence here on github. I would be happy to help if you would like me to.

**Pull request merged**
